version: '3'
services:
  spring-app:
    image: openjdk:11-jdk-slim
    container_name: spring-app-container
    working_dir: /app
    volumes:
      - ./target/AssemblyLanguageParser-0.0.1-SNAPSHOT.jar:/app/AssemblyLanguageParser-0.0.1-SNAPSHOT.jar
      - ./src/main/resources/application.properties:/app/application.properties
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=assembly_language
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Hasanmalai@1996
    command: ["java", "-jar", "AssemblyLanguageParser-0.0.1-SNAPSHOT.jar"]

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=Hasanmalai@1996
      - MYSQL_DATABASE=assembly_language
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Hasanmalai@1996
    ports:
      - "3306:3306"